# permissions for end users to edit demovolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demovolume-editor-role
rules:
- apiGroups:
  - kubebuilder.stephen.demo.io
  resources:
  - demovolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebuilder.stephen.demo.io
  resources:
  - demovolumes/status
  verbs:
  - get
